[package]
name = "rust-uefi-app"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-queue = { version = "0.3.11", features = ["alloc"], default-features = false }
hashbrown = "0.15.2"
log = "0.4.22"
uefi = { version = "0.33.0", features = ["logger", "unstable"] }
uefi-raw = "0.9.0"
